name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Make embedFS happy
        run: mkdir -p ./licensing/my-licenses/ && touch ./licensing/my-licenses/make_embedFS_happy

      - name: Build
        run: mkdir -p ./licensing/my-licenses/ && touch ./licensing/my-licenses/make_embedFS_happy && go build -v ./...

      - name: Test
        run: mkdir -p ./licensing/my-licenses/ && touch ./licensing/my-licenses/make_embedFS_happy && go test -v ./...

